spring.application.name=user-service
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/userdb
spring.datasource.username=root
spring.datasource.password=dPranav301#


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#JWT Properties

# Secret key used to sign and verify the JWT (Must be Base64 encoded or long enough for HS256/HS512)
app.jwt.secret=6b7dd6406b5b13fcf34ed04cb73448aaf2c0d2c41a5067a7314adb67aff6f437

# Token expiration time in milliseconds (e.g., 900000 ms = 15 min)
app.jwt.expiration-ms=900000

# Refresh token expiration time (e.g., 7 days)
app.jwt.refresh-expiration-ms=6048


